### ISSUE TITLE
Which repository is the official one?

### ISSUE THREAD

**Issue by pakmans** [simile-widgets/timeline#2]
http://www.simile-widgets.org/ points to http://code.google.com/p/simile-widgets/source/browse/ while I found this one here which seems to be identical.
Not that it matters much, since it hasn't been updated recently, but just curious.

**Comment by karger** [comment]
The "official" repo (such as there is for open source) is here on github.

**Comment by pakmans** [comment]
Thanks.  By "official" I meant by the original authors and not a fork. For example, I found a a "simile timeline revisited" "fork" here on github (https://github.com/kusog/timeline).
